trigger:
  branches:
    include:
      - latest
  tags:
    include:
      - v*

jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          sudo apt-get install python3-pip -y
          sudo pip3 install --upgrade pip
          sudo pip3 install Sphinx
          sudo apt-get install texlive-full -y
        displayName: install
      - script: |
          make latexpdf
        displayName: build
      - task: GitHubRelease@0
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
        inputs:
          gitHubConnection:  aplqo # add github commection
          repositoryName: aplqo/$(repository_name)
          action: 'create'
          assets: _build/latex/*.pdf
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: _build/latex/*.pdf
