trigger:
  branches:
    include:
      - latest
  tags:
    include:
      - v*

jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          sudo apt-get update
          sudo apt-get install python3-sphinx -y
          sudo apt-get install texlive-full -y
        displayName: install
      - script: |
          make latexpdf
        displayName: build
      - task: GitHubRelease@0
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
        inputs:
          gitHubConnection:  aplqo # add github commection
          repositoryName: '$(Build.Repository.Name)' 
          target: $(Build.SourceVersion)
          tagSource: auto
          action: 'create'
          assets: _build/latex/*.pdf
          releaseNotesSource: 'file'
          releaseNotesFile: ReleaseNote.md
          addChangeLog: true
          compareWith: 'lastFullRelease'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: _build/latex/*.pdf
